// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npvkyiujvxyrrqdyrhas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wdmt5aXVqdnh5cnJxZHlyaGFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNjg5NzYsImV4cCI6MjA3MjY0NDk3Nn0.YSxHEQOACQ7afG9x92nBkpavgqMWzmhyBazs6Agg3aA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});